### PR TITLE
Implemented twitter-settings page.

### PR DESCRIPTION
**Pull request by SezginEge**

### CODE REVIEW

**Comment by gokhangulbiz** [comment]
If you take a look our API error responses, you can understand why there is a field like "FriendlyDescription".

**Comment by SezginEge** [comment]
@gokhangulbiz I understand why there is a field like "FriendlyDescription". You should be more clear. Because at the comment below, You said that "We need a better and more friendly general error message." Now it seems like you've changed your mind. I've tried to implement both FriendlyDescription and General Error together and It also show up friendly description.
 
https://github.com/SezginEge/xomni-cms-vnext/commit/85a9c97984b9c5c54bb97e99d2fb9626bbf59376

**Comment by SezginEge** [comment]
@gokhangulbiz Updated.

**Comment by gokhangulbiz** [comment]
OK, It seems like that I have to explain again, again and again.. Here is my comment,

"We need a better and more friendly general error message. And also we need to differentiate error messages by http status code (5XX,4XX)."

I said "friendly error message". "If you think, you didn't cause this error" is not friendly.

And I said, "differentiate error messages by status code (5XX, 4XX)" As you know (I hope) 4XX means client errors, 5XX means server errors. A simple icon can reflect this behavior to tell the user what is going wrong.

**Comment by gokhangulbiz** [comment]
@daronyondem Could you please review style implementations?

**Comment by SezginEge** [comment]
@daronyondem This pr needs to clean up. But, to follow changes on pr, i didn't do rebase. Let me know when you finished review.

**Comment by daronyondem** [comment]
It looks like the naming convention between the folder holding the HTML file in the project and the file itself has been broken. I was expecting a twitter-settings-page folder holding twitter-settings.html. Instead I see settings-page folder holding a twitter-settings.html. Any particular reason you broke the convention?

I don't see validation in the fields. Is this missing or not implemented in purpose?

The "Save" buttons right border is not aligned to the right end of the gray box surrounding text input controls. 
We need to decrease the amount of space between the horizontal gray line between and the page header, save button.

The header for the page is "Edit Twitter Setttings". This is not the naming convention we used so far. Please remove the "Edit" prefix from the page title.

**Comment by SezginEge** [comment]
@daronyondem There is validation. If one field filled, the others should be filled. You can try that. Just filled one of them and click on the page. 

I fixed naming convention problem. I just thought, I could group every page under the settings. But it is not a right way i guess. :+1:

**Comment by SezginEge** [comment]
@daronyondem Updated.

**Comment by daronyondem** [comment]
Thanks for fixing the folder structure conforming our conventions. Feel free to discuss with your team lead about the value of conventions if you feel the need. I'm sure you will get some good insights that can help you understand why we value conventions.

The validations look good. Thanks.

All the other visual fixes look good as well. Good job.

Can you please double check the committed files in this PR. I see some file changes unrelated to this PR. 

screenshot at may 17 11-33-12

**Comment by SezginEge** [comment]
@daronyondem Unrelated changes comes from #33 . I checked again. Pr looks like messy and very difficult to keep track of changes. When you approved, I will rebase. So, everything will looks fine.

**Comment by daronyondem** [comment]
Please to whatever you need to do implemented the fixes related to my comments and loop me into the appropriate PR. I will label this temp-rej until then. 

Thanks

**Comment by SezginEge** [comment]
@daronyondem Okay. I'm closing this pr. I will make clean up and then send again.

**Comment by SezginEge** [comment]
#44 New pr is here.

**Pull request closed without merging**
