### PR TITLE
Implemented new paginator component

### PR DESCRIPTION
**Pull request by nseckinoral**

### CODE REVIEW

**Comment by nseckinoral** [comment]
@gokhangulbiz I've refactored the codes a bit and fixed various things. Also improved some parts. Plus, tested on other pages to see if styling is okay. Can you take a look?

**Comment by nseckinoral** [comment]
@daronyondem Well I've included the details on my commit message that's why I just tried to give an heads up with a quick comment. Sorry, I'll try to be more spesific next time.

**Comment by nseckinoral** [comment]
@daronyondem Sizin yazıp sildiğinizi gördüm bana mesajı mail'le vermeye çalışıyosunuz diye düşündüm ben de özellikle tek başıma commentleşiyomuşum gibi olmasın diye yazıp sildim hocam :D

**Comment by gokhangulbiz** [comment]
:+1:

**Comment by daronyondem** [comment]
UX Changes are discussed in an offline meeting. @nseckinoral has meeting notes. fyi

**Pull request merged**
