### PR TITLE
Msg integration screen updated.

### PR DESCRIPTION
**Pull request by SezginEge**

### CODE REVIEW

**Comment by ilkayilknur** [comment]
We moved gulp file to deployment folder on Friday. This PR contains broken reference to gulp file.
capture2
 It looks like you added two references of gulpfile in csproj file when resolving conflicts. Can you please fix the references and update PR ?
@daronyondem Removing UX-Approved Flag.

**Comment by daronyondem** [comment]
@ilkayilknur Thx

**Comment by SezginEge** [comment]
@ilkayilknur Ok.

**Comment by SezginEge** [comment]
@daronyondem @ilkayilknur Updated the PR. If you have any problem related this PR, please inform me.

**Comment by daronyondem** [comment]
Thanks. I will definitely let you know if I see a problem related to your PR. It's your PR and I can't think of anyone else I should let know about its problems ;)

**Pull request merged**
