### PR TITLE
Added confirm box feature to message-dialog.

### PR DESCRIPTION
**Pull request by SezginEge**
This PR comes comfirm box feature to message-dialog. You can easily activate comfirm box feature, just sending function with dialog-content. 

To trying PR, You can merge SezginEge:modal-dialog-test and this PR.

### CODE REVIEW

**Comment by daronyondem** [comment]
Sorry, but I can't understand what you are saying there. Can you clarify how we can trigger a Confirm Box and observe how different selections reflect to the output. 

Without a clear understanding of test use cases I will not be able to work on this.

By the way, I understand that SezginEge:modal-dialog-test is a branch on your fork of  https://github.com/XomniCloud/xomni-cms-vnext but it will be much more helpful if you can provide a direct link to a branch https://github.com/SezginEge/xomni-cms-vnext/tree/modal-dialog-test when you refer to it. Without inferring about your intend I have no way of knowing that SezginEge:modal-dialog-test branch resides on your fork of https://github.com/XomniCloud/xomni-cms-vnext

**Comment by SezginEge** [comment]
@daronyondem I'm sorry for that. Next time, I will share more information.
 Let me clarify for you. To try confim box;

* Merge these two branch: https://github.com/SezginEge/xomni-cms-vnext/tree/modal-dialog-test and this PR.
* Open integration-endpoint page on your browser.
* Create integration endpoint.
* Try to delete integration endpoint and you will see confirm box. If you click the "Yes" button, integration endpoint will be deleted. If you click the "No" button, confirm box will be closed.

**Comment by daronyondem** [comment]
When I lunch the page I'm getting the below error;

FriendlyDescription: "Integration endpoint is not enabled on this tenant. Please enable integration endpoint first."
IdentifierGuid: "1fb0024e-53b7-45e8-9457-012c209b146c"
IdentifierTick: 635679791169508700

Additionally something is wrong with the CSS. See below;

screenshot at may 23 15-00-54

I pushed the merged branch I'm using for testing to my fork of xomni-cms-vnext as a separated branch. Feel free to look into it to reproduce the errors I'm having.

Here is the link https://github.com/daronyondem/xomni-cms-vnext/commits/model-dialog-testing

**Comment by SezginEge** [comment]
@daronyondem I couldn't get the error message. Could you please check again? Also, css perfectly normal. Because this PR does not covering integration endpoint styling. This PR adding new feature to message-dialog.

**Comment by daronyondem** [comment]
How can CSS work perfectly when it is not part of this PR as you are suggesting? You are telling me the PR does not contain the styling but still suggesting that it works. Which one should I believe?

It looks like the error is part of the API call and it is expected. Functionally it is not an error. I wish you could clarify that. Anyways, I'm approving this PR for UX. Thanks for the work.

**Comment by daronyondem** [comment]
@ilkayilknur This did not have the Code-Reviewed label. Did you review the code before the merge? Just want to make sure we got our process in place.

**Comment by ilkayilknur** [comment]
@daronyondem yes I reviewed before merging.

**Comment by daronyondem** [comment]
@ilkayilknur Awesome. Thanks.

**Pull request merged**
