### PR TITLE
Fixes #54, added invisible css class to message-diaog, if content doe…

### LINKED ISSUE #54: #confirm div visibility does not changed on message-dialog after the first opening as confirm box.
Normally, message-box should not show up #confirm div for exception messages. But if you used message-dialog as confirm box and then you want to show up exception message, visibility of #confirm div does not change.

### PR DESCRIPTION
**Pull request by SezginEge**
…s not have Click function.

### CODE REVIEW

**Comment by ilkayilknur** [comment]
@daronyondem Can you take a look for UX approval ? Please let me know before testing the PR. I can make some changes on staging environment and you can see the changed error modal dialog easily.

**Comment by daronyondem** [comment]
I don't understand how I'm supposed to test this. 

"added invisible css class to message-diaog, if content does not have Click function"

What content? What click function? How am I going to see the related message-dialiog? What are the QA steps?

**Comment by ilkayilknur** [comment]
We use a generic modal dialog for exception messages and confirm boxes. This PR makes yes&no buttons invisible when showing exception messages.
- Open integration endpoint page and make sure that integration endpoint is in disabled state.
- Open MSG screen and enable MSG integration. 
- You will see a message box that says "Please enable integration endpoint first." This box shouldn't contain yes&no buttons.

**Comment by daronyondem** [comment]
Thanks.

**Pull request merged**
