### PR TITLE
Msg integration screen updated

### PR DESCRIPTION
**Pull request by SezginEge**

### CODE REVIEW

**Comment by daronyondem** [comment]
Assigned this one to @gokhangulbiz for technical review once the back-end requirement are fulfilled. Feel free to assign the PR to me once it is ready for full cycle QA including enable-disable transitions.

**Comment by daronyondem** [comment]
Can you change the target of the MSG link within the text to "_blank". 
When we disable the integration make sure all input fields are cleaned up.

**Comment by daronyondem** [comment]
Looks good! Approved.

**Comment by gokhangulbiz** [comment]
@SezginEge, could you please resolve conflicts?

**Comment by SezginEge** [comment]
@gokhangulbiz Conflicts resolved.

**Comment by SezginEge** [comment]
This PR contains xomni.d.ts, xomni.js, xomni.js.map and packages.config. But actually, it should not contains these files. So i'm closing PR.New PR is here #51.

**Pull request closed without merging**
