### PR TITLE
Implemented facebook-settings page.

### PR DESCRIPTION
**Pull request by SezginEge**

### CODE REVIEW

**Comment by gokhangulbiz** [comment]
@daronyondem Could you please review style implementations?

**Comment by daronyondem** [comment]
@gokhangulbiz I appreciate the comment and mention. Additionally can you please assign the item to me when you need any type of action from my end. Thanks.

**Comment by SezginEge** [comment]
@daronyondem This pr needs to clean up. But, to follow changes on pr, i didn't do rebase. Let me know when you finished review.

**Comment by daronyondem** [comment]
The "save" buttons right border is not aligned to the right end of the gray box surrounding text input controls. 
We need to decrease the amount of space between the horizontal gray line between and the page header, save button.

Can we make the dropdowns expend according to their content instead of 100% enlargement.

The header for the page is "Edit Facebook Setttings". This is not the naming convention we used so far. Please remove the "Edit" prefix from the page title.

What about adding a success page when the save is successful? We will need to do this for all of our screens if we decide to. /cc @gokhangulbiz @ilkayilknur

**Comment by SezginEge** [comment]
@daronyondem Updated.

**Comment by daronyondem** [comment]
I was not able to run this locally on my end. Can you double check if you are able to navigate to http://localhost/XOMNI.CMS.FrontEnd/src/#management/facebook-settings through the routing. Let me know if I'm missing anything. 

Thanks

**Comment by SezginEge** [comment]
I am able to navigate facebook-settings page. Please try clean solution and rebuild it. Also, don't remember to disable the cache.

**Comment by daronyondem** [comment]
All looks good. 

Is there a way to change how the popup listbox is being displayed in this dropdown?

screenshot at may 17 17-10-11

Maybe some margin between the items in the listbox?

**Comment by SezginEge** [comment]
@daronyondem It seems webkit browsers does not support styling of option tags. If you need some margins between the items in the listbox, I can make custom control. But it will take a time :/

**Comment by daronyondem** [comment]
Can you add a time-boxed research item to your backlog to come up with options and estimates for this. That way we will have a chance to decide which path to proceed. 

Thanks.

I'm assigning this back to @gokhangulbiz so he can proceed with the merge. Let me know if you need anything else from me.

**Comment by SezginEge** [comment]
@daronyondem  Thanks. I'm closing this pr. I will clean up and send again.

**Comment by SezginEge** [comment]
New PR is here #61.

**Pull request closed without merging**
