### PR TITLE
Applied css to msg-integration screen.

### PR DESCRIPTION
**Pull request by SezginEge**

### CODE REVIEW

**Comment by gokhangulbiz** [comment]
@daronyondem Could you please review style implementations?

**Comment by SezginEge** [comment]
@daronyondem This pr needs to clean up. But, to follow changes on pr,  i didn't do rebase. Let me know when you finished review.

**Comment by daronyondem** [comment]
The "Enable" buttons right border is not aligned to the right end of the gray box surrounding text input controls. 
We need to decrease the amount of space between the horizontal gray line between and the page header, enable button.
When I Enabled MSG Integration for the test environment I did not receive a success message. I was able to enable it thousands of times.  @gokhangulbiz Is this expected for the test environment? I would like to see what happens after I click the "Enable" button.

**Comment by SezginEge** [comment]
@daronyondem Updated.

**Comment by daronyondem** [comment]
Thanks for all the changes @SezginEge All look good.

I'm still not able to test the post-enablement scenario. Maybe the error in the screenshot might help you understand the problem. I will not be able to approve this PR unless I can test the full cycle. 

screenshot at may 17 11-37-42

**Comment by SezginEge** [comment]
@daronyondem I didn't make any changes on msg-integration.ts file that may cause these problems. I guess, I can not solve these problems. These errors coming from api. Am I wrong? @gokhangulbiz @ilkayilknur

**Comment by ilkayilknur** [comment]
@daronyondem In order to test msg-enablement scenario, we need to deploy API Management recent Rest API Changes to staging environment.I've enabled msg-integration manually for you to check post-enablement scenario in page. However, it's look like page doesn't load current msg-integration status. 
@SezginEge  Can you please test the page again against to staging tenant before @daronyondem 's test.? I'm getting some errors.

capture

**Comment by SezginEge** [comment]
@ilkayilknur I'm able to  test the post-enablement scenario and not getting any errors. Could you please try clean solution and rebuild? Please don't remember to disable cache.  Thank you for helping.

**Comment by daronyondem** [comment]
Thanks for the help @ilkayilknur 

@SezginEge 

The password column is empty. As far as I can see there is no way to edit the password as well. Considering we are not showing an edit box for the password and we don't show the password at all why do we have the column at first?

Is there a way to reveal the password that I'm missing? If not, how do I reset it? If I can't how do I disable the MSG Integration? 

Underneath the column "Portal URL" we are not providing a URL. We are providing an access link with the URL embedded into it. Can we change the column name to "Portal Access" to suit the content of the column please.

Finally, I need to see the interaction from "not enabled" to "enabled" Right now I have access to the "enabled" state of the page but can't see how the transition experience is. I need to see it.

Just one final note; before the page successfully loads the MSG enablement status I keep seeing the textboxes for the first name, last name and e-mail. Instead I should see a progress dialog where it says the page is loaded the status of the MSG Integration. Afterwards we can populate the textboxes or the grid to show appropriate content.

Thanks for all the hard work guys. Keep it up.

**Comment by SezginEge** [comment]
@daronyondem I didn't remove any column/button etc. or add. Because I just give a new look to msg-integration screen. I updated existing screen.

Okay. I will make changes that you said. Thanks for feedback.

**Comment by daronyondem** [comment]
Thanks for the insight @SezginEge  I need you to use your own judgement while migrating these pages into vNext. Feel free to ask your potential questions to your Product Owner when you feel the need. I know you can do more. We are definitely not asking you to be a mindless cloner ;) It's your fight. Keep it up.

**Comment by SezginEge** [comment]
@daronyondem I updated pr. :+1: 

You can't see the interaction from "disabled" to "enabled" because it is not implemented yet. Also there is a bug. 

Modal popup does not work, If you refresh the page. Bug is not related this pr directly. So, I'm opening an issue.

**Comment by daronyondem** [comment]
I understand. I can't approve this PR unless the "disabled" to "enabled" transition is implemented. Feel free to bump this PR when it is with the updated content. Thanks.

In the context of your internal backlog, If your PBI does not include the transition part of this screen please inform your PO that the rest of the implementation is ok. From my perspective I don't feel comfortable merging a half implementation into the dev branch. 

Thanks

**Comment by SezginEge** [comment]
@daronyondem Thanks.

**Comment by SezginEge** [comment]
#43 New pr is here.

**Pull request closed without merging**
