### PR TITLE
Implemented info box for trending-action-settings page

### PR DESCRIPTION
**Pull request by nseckinoral**

### CODE REVIEW

**Comment by ilkayilknur** [comment]
We need to open developer portal links in a new tab. Can you update the link ?

**Comment by nseckinoral** [comment]
@ilkayilknur  I'm on it.

**Comment by nseckinoral** [comment]
@ilkayilknur Updated. Can you take a look at my last commit please?

**Comment by ilkayilknur** [comment]
@nseckinoral Thanks. LGTM. @daronyondem  can you take a look ?

**Pull request merged**
