### PR TITLE
Applied css msg-integration screen.

### PR DESCRIPTION
**Pull request by SezginEge**

### CODE REVIEW

**Comment by daronyondem** [comment]
copy-past from #33 for the sake of context;

I can't approve this PR unless the "disabled" to "enabled" transition is implemented. Feel free to bump this PR when it is with the updated content. Thanks.

In the context of your internal backlog, If your PBI does not include the transition part of this screen please inform your PO that the rest of the implementation is ok. From my perspective I don't feel comfortable merging a half implementation into the dev branch.

Thanks

**Comment by gokhangulbiz** [comment]
OK. Reverted to 69eeacddd8cf10c124173c5a0bd179e9e9030b23

**Comment by daronyondem** [comment]
Thanks. Appreciate the help.

**Comment by SezginEge** [comment]
@daronyondem Updated the pr. But you can't still try disable to enable feature. Because, We haven't deployed APIs to staging environment yet. Also can you review this pr with considering #45 ?

**Comment by SezginEge** [comment]
@daronyondem I have seperated the PR. #46 contains modal-dialog implementation and fix of #45. #47 contains msg-integration css styling. .

**Comment by daronyondem** [comment]
Thanks for the effort. This looks much better.

**Pull request closed without merging**
