### PR TITLE
message-dialog implemented.

### PR DESCRIPTION
**Pull request by SezginEge**
Replacing the error-dialog with a more generic message-dialog implementation.

### CODE REVIEW

**Comment by daronyondem** [comment]
I need to know how to test this one from a QA perspective. Let me know which reproduction steps are suitable to get to both to an error dialog and message dialog within this PRs originating branch. 

Thanks

**Comment by daronyondem** [comment]
It looks like this PR fixes #45 . Make sure you mention and close the issue when you merge this one.

Thanks

**Comment by SezginEge** [comment]
If you want to try original error dialog;
* Checkout dev branch
* Open msg-integration page 
* Open developer console and run the following commands.
* * $('#dialogContent').text("Body")
* * $('#genericDialog').modal()

If you want to try message-dialog;
* Pull this pr on your computer
* Open msg-integration page
* Open developer console and run the following commands.

For try the success case, run the following command.
* $('#header').addClass('successfull'); 
* $('#title').text("Title")
* $('#dialogContent').html("Body")
* $('#genericDialog').modal()

For try the warning case, run the following command.
* $('#header').addClass('warning'); 
* $('#title').text("Title")
* $('#dialogContent').html("Body")
* $('#genericDialog').modal()

For try the error case, run the following command.
* $('#header').addClass('error'); 
* $('#title').text("Title")
* $('#dialogContent').html("Body")
* $('#genericDialog').modal()

**Comment by daronyondem** [comment]
Awesome! Approved.

**Pull request closed without merging**
